### PR TITLE
Gio's commit

### PR DESCRIPTION
**Pull request by giovannfox**

### CODE REVIEW

**Comment by juanbecerra0** [comment]
Gio,

When compiling GioFox.java, an error is thrown since the public class's name does not match the file's name. I'd suggest changing:

`public class Test {`

to:

`public class GioFox`

since Test.java already exists.

**Comment by juanbecerra0** [comment]
In addition, your function call:

`
console.log(giovann.helloWorld);
`

yields undefined behavior. This is because your "helloWorld" function has no return value. Rather, it simply prints "Hello World" to the console. You can fix this by either invoking helloWorld as a function like this

`
giovann.helloWorld();
`

or changing your function to simply return a string, like this

`
function helloWorld() {
    return "Hello World!";
}
`

**Comment by iamamonte** [comment]
Please make the requested changes.

**Comment by giovannfox** [comment]
I will today, thank you!

**Comment by giovannfox** [comment]
Hello,

Just fixed the errors, thank you Juan for the help! 

Sincerely,
Giovann Fox

**Comment by iamamonte** [comment]
Giovann, sorry for the confusion. You still need to modify the call to your function in comment-practice. As it stands now, you're not causing the function to be executed. 

Please see this document for more information: https://javascript.info/function-expressions

**Comment by giovannfox** [comment]
Thank you Amonte I’ll fix that right away!

**Comment by giovannfox** [comment]
fixed

**Pull request merged**
